version: "3"

services:
    api:
        container_name: fastFood-api
        build: "."
        working_dir: /fastFood
        volumes:
            - ./:/node-app
            - ./node_modules:/node-app/node_modules
        environment:
            NODE_ENV: development
            MONGODB_CONN_STRING: mongodb://db:27017
        restart: always
        command: sh -c "npm run start"
        depends_on:
            - db
        links:
            - db
        ports:
            - "6001:6001"
        networks:
            - fastFoodNetwork

    db:
        container_name: fastFood-mongodb
        image: mongo:latest
        ports:
            - "27017:27017"
        volumes:
            - ./data/db:/data/db
        networks:
            - fastFoodNetwork

networks:
  fastFoodNetwork:
    driver: bridge
