version: "3"

services:
    db:
        container_name: fastFoodMongodb
        image: mongo:latest
        ports:
            - "27017:27017"
        volumes:
            - ./data/db:/data/db
        networks:
            - fastFoodNetwork
    api:
        container_name: fastFoodApi
        build: "."
        working_dir: /fastFood
        environment:
            NODE_ENV: development
            MONGODB_CONN_STRING: mongodb://db:27017
        command: sh -c "npm run start"
        depends_on:
            - db
        links:
            - db
        ports:
            - "6001:6001"
        networks:
            - fastFoodNetwork
    db-import:
        container_name: fastFoodImport
        image: mongo:latest
        depends_on:
            - db
        links:
            - db
        volumes:
            - ./data-import:/data-import
        networks:
            - fastFoodNetwork
        restart: "no"
        command: >
            sh -c "mongoimport --host=db --db=fast_food --collection clientes --type json --file /data-import/clientes.json --jsonArray 
            && mongoimport --host=db --db=fast_food --collection produtos --type json --file /data-import/produtos.json --jsonArray"

networks:
    fastFoodNetwork:
        driver: bridge
