apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mongo
  labels:
    name: pv-mongo
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage-db 
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /run/desktop/mnt/host/d/Users/Daniel/Documents/FIAP/tech-challenge/data